// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package frc.robot.subsystems;

import frc.robot.Robot;
import frc.robot.RobotMap;
import edu.wpi.first.wpilibj.command.Subsystem;
import edu.wpi.first.wpilibj.SpeedController;

// END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS


/**
 *
 */
public class HatchHand extends Subsystem {

    private final SpeedController extender = RobotMap.armHand;


    private double speed;
    
    @Override
    public void initDefaultCommand() {
        // Set the default command for a subsystem here.
        // setDefaultCommand(new MySpecialCommand());
    }

    @Override
    public void periodic() {
        // Put code here to be run every loop

    	// speed = Robot.m_oi.getSpeed();
    	speed = .78;
    	
    	if (Robot.m_oi.getHandOpen()) {
    		System.out.println("Hand Open button pressed, speed = "+ speed);
    		extender.set(speed);
    		
    	} else if (Robot.m_oi.getHandClose()) {
    		System.out.println("Hand Close button pressed, speed = "+ -1.0*speed);
    		extender.set(-1.0*speed);
    		
    	} else {
    		
    		extender.set(0);
    		
    	}
    	
    }

    // Put methods for controlling this subsystem
    // here. Call these from Commands.

}